pipeline {
    agent any

    stages {
        stage('Deploy Nagios via Helm') {
            steps {
                sh '''
                    # Add Helm repository
                    helm repo add cetic https://cetic.github.io/helm-charts
                    helm repo update

                    # Create namespace if it does not exist
                    kubectl create namespace nagios --dry-run=client -o yaml | kubectl apply -f -

                    # Upgrade or install Nagios using values.yaml inside Nagios-Helml folder
                    helm upgrade --install nagios cetic/nagios --namespace nagios -f Nagios-Helml/values.yaml
                '''
            }
        }
    }
}