pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: nagios-helm-agent
spec:
  containers:
  - name: helm
    image: alpine/helm:latest
    command:
    - cat
    tty: true
'''
        }
    }

    stages {
        stage('Deploy Nagios via Helm') {
            steps {
                container('helm') {
                    sh '''
                        # Add Helm repository
                        helm repo add cetic https://cetic.github.io/helm-charts
                        helm repo update

                        # Upgrade or install Nagios using values.yaml inside Nagios-Helml folder
                        helm upgrade --install nagios cetic/nagios \
                          --namespace nagios \
                          --create-namespace \
                          -f Nagios-Helml/values.yaml
                    '''
                }
            }
        }
    }
}